[package]
name = "firmware-controller"
description = "Controller to centralize interaction with HW in a firmware"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["extra-traits", "fold", "full"] }
